name: Keep Streamlit Apps Alive

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright (Python) + system deps + Chromium
        run: |
          pip install --upgrade pip
          pip install playwright
          # instala dependencias del SO adecuadas para esta distro
          sudo python -m playwright install-deps chromium
          # instala el navegador
          python -m playwright install chromium

      - name: Visit Streamlit apps
        env:
          APP_URLS: |
            https://optibat-metrics-dashboard-flags.streamlit.app/
            https://optimitive-eda-analyzer.streamlit.app/
        run: |
          python - <<'PY'
          import os, time
          from playwright.sync_api import sync_playwright

          urls = [u.strip() for u in os.environ["APP_URLS"].splitlines() if u.strip()]

          def visit(page, url):
              print(f"Visitando: {url}")
              page.goto(url, wait_until="domcontentloaded", timeout=180000)
              html = page.content()
              if "wake it back up" in html or "Zzzz" in html:
                  print("→ App dormida: despertando…")
                  try:
                      page.get_by_role("button", name="Yes, get this app back up!").click()
                  except:
                      page.click("text=back up")
                  page.wait_for_load_state("networkidle", timeout=240000)
              else:
                  page.wait_for_load_state("networkidle", timeout=180000)
              print(f"✔ OK: {url}")

          with sync_playwright() as p:
              browser = p.chromium.launch(headless=True)
              for url in urls:
                  ctx = browser.new_context()
                  page = ctx.new_page()
                  for i in range(2):
                      try:
                          visit(page, url); break
                      except Exception as e:
                          print(f"Intento {i+1} falló: {e}")
                          time.sleep(12)
                  ctx.close()
              browser.close()
          PY
